### ISSUE TITLE
Need help on serverless deploy using Mangum as adapter.

### ISSUE THREAD

**Issue by neko1101** [jordaneremieff/mangum#135]
Good day guys!

I have some issues deploying using serverless framework (AWS Lamda).

AWS Cloudwatch Logs for the Lamda:
```
[ERROR] AttributeError: module 'typing' has no attribute '_ClassVar'
Traceback (most recent call last):
  File "/var/lang/lib/python3.8/imp.py", line 234, in load_module
    return load_source(name, filename, file)
  File "/var/lang/lib/python3.8/imp.py", line 171, in load_source
    module = _load(spec)
  File "<frozen importlib._bootstrap>", line 702, in _load
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 783, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/var/task/app/main.py", line 5, in <module>
    from mangum import Mangum
  File "/var/task/mangum/__init__.py", line 1, in <module>
    from .adapter import Mangum
  File "/var/task/mangum/adapter.py", line 11, in <module>
    from mangum.protocols.lifespan import LifespanCycle
  File "/var/task/mangum/protocols/lifespan.py", line 37, in <module>
    class LifespanCycle:
  File "/var/task/dataclasses.py", line 958, in dataclass
    return wrap(_cls)
  File "/var/task/dataclasses.py", line 950, in wrap
    return _process_class(cls, init, repr, eq, order, unsafe_hash, frozen)
  File "/var/task/dataclasses.py", line 800, in _process_class
    cls_fields = [_get_field(cls, name, type)
  File "/var/task/dataclasses.py", line 800, in <listcomp>
    cls_fields = [_get_field(cls, name, type)
  File "/var/task/dataclasses.py", line 659, in _get_field
    if (_is_classvar(a_type, typing)
  File "/var/task/dataclasses.py", line 550, in _is_classvar
    return type(a_type) is typing._ClassVar
```

According to (https://fernandomc.com/posts/issues-with-typing-python-3/) this is caused by `typing` module conflict.

I've tried to exclude/uninstall the module but no luck at all, can someone show me some lights? I'm happy to give more info as per your request...

For anyone familiar with serverless lamda, the serverless.yml included this:
```
custom:
  pythonRequirements:
    dockerizePip: non-linux
    noDeploy:
      - typing
```

Sankyu!

**Comment by jordaneremieff** [comment]
@neko1101 Hello. What Python runtime version are you using, and could you post a minimal example of an application & serverless configuration I can use to reproduce this?

**Comment by neko1101** [comment]
Running python =<3.6 solved it!
@jordaneremieff thanks for your reply!
