### ISSUE TITLE
0.13 breaks `lifespan` behaviour

### ISSUE THREAD

**Issue by vincentsarago** [jordaneremieff/mangum#243]
First reported in https://github.com/developmentseed/eoAPI/issues/34

When using the latest mangum release `0.13` it seems that my `Life Cycle Hooks` are ran before the handler. I have a limited knowledge in ASGI so I'm sorry if I'm not explaining the issue the best way.

👇 Here is the minimal application which I used to reproduce the issue.

```python
from mangum import Mangum
from starlette.requests import Request
from fastapi import FastAPI

app = FastAPI()
@app.get("/yo")
async def ping(request: Request):
    """Health check."""
    return request.app.state.v

@app.on_event("startup")
async def startup_event() -> None:
    """Connect to database on startup."""
    app.state.v = "In"

@app.on_event("shutdown")
async def shutdown_event() -> None:
    """Close database connection."""
    app.state.v = "Out"

handler = Mangum(app, lifespan="auto")
```

☝️ this simple app return `In` for mangum=0.12.4 and `Out` for mangum=0.13. 

When setting `lifespan="off"` I'm getting `Internal Server Error` 

```
[ERROR]	2022-03-01T22:13:19.759Z	45e46869-c976-4f32-bd3d-cab179cf8caf	Exception in 'http' protocol.
Traceback (most recent call last):
  File "/var/task/starlette/datastructures.py", line 661, in __getattr__
    return self._state[key]
KeyError: 'v'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/var/task/mangum/protocols/http.py", line 81, in run
    await app(self.request.scope, self.receive, self.send)
  File "/var/task/fastapi/applications.py", line 259, in __call__
    await super().__call__(scope, receive, send)
  File "/var/task/starlette/applications.py", line 112, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/var/task/starlette/middleware/errors.py", line 181, in __call__
    raise exc
  File "/var/task/starlette/middleware/errors.py", line 159, in __call__
    await self.app(scope, receive, _send)
  File "/var/task/starlette/exceptions.py", line 82, in __call__
    raise exc
  File "/var/task/starlette/exceptions.py", line 71, in __call__
    await self.app(scope, receive, sender)
  File "/var/task/fastapi/middleware/asyncexitstack.py", line 21, in __call__
    raise e
  File "/var/task/fastapi/middleware/asyncexitstack.py", line 18, in __call__
    await self.app(scope, receive, send)
  File "/var/task/starlette/routing.py", line 656, in __call__
    await route.handle(scope, receive, send)
  File "/var/task/starlette/routing.py", line 259, in handle
    await self.app(scope, receive, send)
  File "/var/task/starlette/routing.py", line 61, in app
    response = await func(request)
  File "/var/task/fastapi/routing.py", line 227, in app
    raw_response = await run_endpoint_function(
  File "/var/task/fastapi/routing.py", line 160, in run_endpoint_function
    return await dependant.call(**values)
  File "/var/task/handler.py", line 16, in ping
    return request.app.state.v
  File "/var/task/starlette/datastructures.py", line 664, in __getattr__
    raise AttributeError(message.format(self.__class__.__name__, key))
AttributeError: 'State' object has no attribute 'v'
```

When setting `lifespan="on"`, I'm seeing the same result as with `auto`

**Comment by jordaneremieff** [comment]
Hi @vincentsarago, thanks for all the details.

I had suspected this might be the case because in my previous refactoring I had moved the handler call out of the context manager for lifespan mistakenly, though was not sure if this was actually a breaking change when I realised it initially.

Could you test your app using the code currently in the `main` branch? If that resolves it then I'll do a release in the next day or two, otherwise if that is still breaking I'll investigate it further.

**Comment by vincentsarago** [comment]
@jordaneremieff 🙏 using `main` works. 

fixed in https://github.com/jordaneremieff/mangum/commit/7ee6846f2c90815dd7d1e12607e8226bbb0058d9
